### PR TITLE
LL4225 - remove link to account when in walletconnect mode

### PR DESCRIPTION
**Pull request by machard**
https://ledgerhq.atlassian.net/browse/LL-4225

### CODE REVIEW

**Review by gre — DISMISSED** [review]
I find the implementation a bit weird (opération détails don't strictly depends on walletconnect)

I would prefer we add in the navigation object a flag like "disableAllNavigations"

**Comment by machard** [comment]
when launching the send fund flow, or when going to the operation details page ?

(I usually go with the easy way until it makes my life complicated ^^. I would say that I consider creating a new concept when the easy way starts to be annoying)

**Comment by gre** [comment]
I think you simply can add it in the `navigate("OperationDetail", { flag here })` (pseudo code)
i think it's better because that makes the screens more uncoupled (and for instance, we could test the screen individually without it being implicitly depending on WC)

**Review by gre — APPROVED** [review]

**Review by Arnaud97234 — APPROVED** [review]

**Comment by gre** [comment]
shipped by https://github.com/LedgerHQ/ledger-live-mobile/pull/1545

**Pull request closed without merging**
