### PR TITLE
LL-3363 Fix for experimental device action being active by default

### PR DESCRIPTION
**Pull request by juan-cortes**
Introduces the experimental device flow for opening applications (prompting the user to open) on the device. It takes forever to work though so perhaps we should consider improving the performance. According to my testing it's somewhere between 16 and 18 seconds between the user accepting on the device and the import continuing, which is huge.

### Type
Feature

### Context
https://ledgerhq.atlassian.net/browse/LL-3363

### Parts of the app affected / Test plan
- Launch LLM
- Go into a flow the requires to be on a currency app
- Test the behaviour while being on the dashboard/inside another app/etc

### CODE REVIEW

**Review by gre — DISMISSED** [review]

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
### Bug found
When a currency app is missing on the device and user go to Add Account flow for that currency:

**Comment by juan-cortes** [comment]
I'm checking @Arnaud97234

**Comment by juan-cortes** [comment]
Good catch, something like https://github.com/LedgerHQ/ledger-live-common/pull/906 should be merged on live-common in order to prevent this

**Comment by gre** [comment]
@juan-cortes tomorrow you can release a new livecommon , you will need to bump all @ledgerhq/ libs

**Review by gre — APPROVED** [review]

**Review by Arnaud97234 — APPROVED** [review]

**Pull request merged**
