### PR TITLE
LL-7057 Elrond sync/send/receive

### PR DESCRIPTION
**Pull request by ghost**
## 🦒 Context (issues, jira)

https://ledgerhq.atlassian.net/browse/LL-7057

## 💻  Description / Demo (image or video)

1st step of [Elrond](https://docs.elrond.com/) integration into LL, with only sync/send/receive support.

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

### CODE REVIEW

**Comment by haammar-ledger** [comment]
Currency is currently unactivated (removed from supported currencies) - TBD if we activate it before merge or not.

**Review by LFBarreto — APPROVED** [review]
:rocket:

**Review by gre — CHANGES_REQUESTED** [review]
CI ko

**Review by gre — APPROVED** [review]
CI ok

**Pull request merged**
