### PR TITLE
Autolock loop - Simplified the autolock logic, removed the timeout

### PR DESCRIPTION
**Pull request by juan-cortes**
The app state cycle was a bit messy and the `setTimeout` wasn't triggering consistently. Since it wasn't working at all on iOS and we had a little delay when coming back until it was locked (that was deemed acceptable at the time) and since Android handles the events differently and locks a lot faster I simplified the logic a lot, removing the timeout and handling the app state changes tighter.

This should fix the lock loop that @aramab was experiencing and also make the autolock work more consistently in both platforms.

image

### CODE REVIEW

**Comment by gre** [comment]
@juan-cortes can you squash into one commit so it's easier to cherry-pick? i'll cherry-pick from master on monday so we do the patch release

**Comment by juan-cortes** [comment]
@arnaud97234 doubt I can do anything about that, @gre I will squash later, sure

**Comment by gre** [comment]
It's an interesting feedback but I don't feel it's a regression right?
Nevertheless, let's add this in our backlog.

One idea to fix this is to delay the splashscreen.show() , even tho I'm not even sure if it's used at this time but that's my first blind guess

**Comment by juan-cortes** [comment]
I'll take a look tonight, maybe I can do something about it, but I think it's just the time it takes for the unlock to do its thing. I'll give it a couple hours see what comes out of it

**Comment by juan-cortes** [comment]
I'll take a look tonight, maybe I can do something about it, but I think it's just the time it takes for the unlock to do its thing. I'll give it a couple hours see what comes out of it

**Comment by juan-cortes** [comment]
It might be possible to use the app state changes to animate an overlay that hides that screen if it's an issue or the sensitive data that could be seen in that fraction of time that it takes to lock, I tested a bit the idea and it should be doable. I say **keep it as it is**, and see what kind of feedback from the community we get. See if it's an issue at all.

@gre squashed into a cherry-pickable commit

**Comment by gre** [comment]
You don't need to implement an overlay btw. It's already what splashscreen.show() and hide () does

And btw we already have a timeout of 300ms today. Maybe you want to try increasing that. See code of src/index

**Comment by juan-cortes** [comment]
afaik the splashscreen is only used from the `onRebootStart` from js and natively called at launch, so unless we are doing a resetAll or clear data, the splash wouldn't show? Maybe I'm misunderstanding it, I was playing with the idea of showing something that fades into transparency on unlock, but it's probably not even worth it

**Comment by gre** [comment]
In Arnaud gif we see the splash screen appearing no? 🤔

**Comment by juan-cortes** [comment]
Then I'm all confused again! I don't get the splash on an autolock -.-

**Comment by gre** [comment]
I suspect it's only happening if you come back after a long term (app reboot)
So yeah, not tricky to solve , let's leave that in a backlog task as initially said ;)

**Pull request merged**
