### PR TITLE
Bump minor/patch of many dependencies

### PR DESCRIPTION
**Pull request by gre**
synchronize the project with recent library fixes.

This also potentially fixes LL-1041 because the race condition fixes in live-common.

### Type

bumps

### Parts of the app affected / Test plan

Everything.

we need to carefully test the app still works fine on Android and iOS.

### CODE REVIEW

**Comment by gre** [comment]
i'm flagging this as important because it's good to do it at the beginning of this sprint.

**Comment by gre** [comment]
ok so Arnaud is seeing too much bugs on this. we'll do bumps step by step. starting with the live-common stuff

**Comment by Arnaud97234** [comment]
**Bugs found**
1) ios
Send -> When user is on Verification screen, from time to time the verification infos are not displayed on device (wallet app is opened but nothing happen on device) :

img_0076

Then user exit the wallet app on device and the following error is occurring :

img_0077

The following error should be displayed :

img_1ad6df018478-1
____
2) Android
yarn android result in error :

```
Task :react-native-keychain:compileDebugJavaWithJavac FAILED
/Users/aulric/Workspace/repos/ledger-live-mobile/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java:28: error: cannot find symbol
import android.security.keystore.StrongBoxUnavailableException;
                                ^
  symbol:   class StrongBoxUnavailableException
  location: package android.security.keystore
/Users/aulric/Workspace/repos/ledger-live-mobile/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java:266: error: cannot find symbol
    @TargetApi(Build.VERSION_CODES.P)
                                  ^
  symbol:   variable P
  location: class VERSION_CODES
/Users/aulric/Workspace/repos/ledger-live-mobile/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java:270: error: cannot find symbol
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.P) {
                                                       ^
  symbol:   variable P
  location: class VERSION_CODES
/Users/aulric/Workspace/repos/ledger-live-mobile/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java:274: error: cannot find symbol
            return generateKey(getKeyGenSpecBuilder(service).setIsStrongBoxBacked(true).build());
                                                            ^
  symbol:   method setIsStrongBoxBacked(boolean)
  location: class Builder
/Users/aulric/Workspace/repos/ledger-live-mobile/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java:275: error: cannot find symbol
        } catch (StrongBoxUnavailableException e) {
                 ^
  symbol:   class StrongBoxUnavailableException
  location: class CipherStorageKeystoreAESCBC
5 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-keychain:compileDebugJavaWithJavac'.
```

**Comment by gre** [comment]
thanks for the feedback @Arnaud97234 it will be useful to identify what problem we'll have to solve next time we try to bump these

**Pull request closed without merging**
