### PR TITLE
LL-9214 remove metro.config.js

### PR DESCRIPTION
**Pull request by henri-ly**
### Type

BugFix

### Context

https://ledgerhq.atlassian.net/browse/LL-9214

I really don't know why it wasn't needed anymore. Do we change thing on polyfill or smth ? 

### Parts of the app affected / Test plan

XRP and DOT

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by gre — APPROVED** [review]

**Review by valpinkman — APPROVED** [review]

**Comment by haammar-ledger** [comment]
(Has been validated here already: https://github.com/LedgerHQ/ledger-live-mobile/pull/2194)

**Review by ghost — APPROVED** [review]

**Review by juan-cortes — APPROVED** [review]
I lack visibility on what this is but I trust the reviews of @gre and @haammar-ledger , approving to unlock

**Comment by henrily-ledger** [comment]
This one is already merged on release/2.38.x i'm lost with the process rn ? Should we merged this one also

**Review by ychen-ledger — APPROVED** [review]
Same fix as PR https://github.com/LedgerHQ/ledger-live-mobile/pull/2194 which already merge in release branch, as XRP is instability all rest issues will be fix in other ticket

**Pull request merged**
