### PR TITLE
BLE performance optimisations

### PR DESCRIPTION
**Pull request by gre**
This adds back the logic to pause the background synchronisation of accounts during critical phases like Manager or device flows.

It also includes this work: https://github.com/LedgerHQ/ledger-live-common/releases/tag/v19.11.0

### CODE REVIEW

**Review by juan-cortes — CHANGES_REQUESTED** [review]
While this would fix instability issues in some cases, it would not fix it for swap since it seems to be using `ModalBottomAction` and not `DeviceActionModal`. We either need to add it to that too (via a prop or something) or refactor the confirmation for swap so that it uses `DeviceActionModal`

The reason it's not using a simple `DeviceActionModal` is that for swap confirmation we are chaining several things, the initSwap action and the sign, and broadcast parts.

**Comment by gre** [comment]
@juan-cortes should be covered now

**Comment by juan-cortes** [comment]
> @juan-cortes should be covered now

Awesome

**Review by juan-cortes — DISMISSED** [review]
🚀

**Review by nabil-brn — CHANGES_REQUESTED** [review]
I don't know if it's on develop branch but the experimental header is displayed on the drawers.

Screenshot_20210531-180755_LL  STAGING
---
6952f2727 (HEAD -> LL-5685, upstream/LL-5685) update live-common

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
See comment in https://ledgerhq.atlassian.net/browse/LL-5781

**Review by JunichiSugiura — COMMENTED** [review]
LGTM

**Comment by Arnaud97234** [comment]
Last remaining topic for BLE disconnection: https://ledgerhq.atlassian.net/browse/LL-5801/ It's not a blocker. We can merge

**Review by Arnaud97234 — APPROVED** [review]

**Review by MortalKastor — APPROVED** [review]

**Review by valpinkman — APPROVED** [review]

**Review by LFBarreto — APPROVED** [review]

**Pull request merged**
