### PR TITLE
LL-5852 - Update fab buy target

### PR DESCRIPTION
**Pull request by machard**
https://ledgerhq.atlassian.net/browse/LL-5852

### CODE REVIEW

**Review by LFBarreto — CHANGES_REQUESTED** [review]
Can you create a separate PR with the ios updates? i don't think its needed for this specific issue :+1:

**Comment by machard** [comment]
yes i did, but then i need it to be merged, until then i cant work. so thats why its there

**Comment by machard** [comment]
https://github.com/LedgerHQ/ledger-live-mobile/pull/1755

**Comment by gre** [comment]
@machard i merged it. please update. thanks.

**Pull request closed without merging**
