### PR TITLE
LL-9022 - Improve legibility of app sizes in the manager for LNS+

### PR DESCRIPTION
**Pull request by tlaforge-ledger**
### Type

Feature improvement

### Context
https://ledgerhq.atlassian.net/browse/LL-9022

1 - New device has more precise values data about storage (apps, firmware allocation, free space, etc...). We don't really need it on UI side for now. So we have to control the precision and the values to show.
2 - We wanted to better handle the rounding of data being less optimistic. When we are showing data about used space, we want to ceil the value and when it's about free space we will floor it to always unsure user will not be surprised thinking he could install something but when I do it, it fails cause missing few bytes on nano device.

### Parts of the app affected / Test plan

1 - Use a nano SP and go to the manager
2 - Check it works with other devices

### CODE REVIEW

**Review by gre — DISMISSED** [review]
(prettier to run)

**Comment by juan-cortes** [comment]
Please try adding some description, a pretty screenshot, and how to test this easily @tlaforge-ledger it goes a long way for others to know what this is about without having to read a, potentially long, Jira task.

**Comment by juan-cortes** [comment]
Like I asked for, two months ago, please update the PR with context, description and screenshots. @tlaforge-ledger

Since the PR is now very outdated, rebase (or reset like on LLD) and request a review again. Ping me when it's ready for review

**Review by juan-cortes — APPROVED** [review]
lgtm

**Comment by juan-cortes** [comment]
I updated the Jira task since we split LLD and LLM onces

**Comment by juan-cortes** [comment]
I can't merge but it's in QA OK @gre

**Review by LFBarreto — APPROVED** [review]

**Pull request merged**
