### PR TITLE
bump live-common / libcore. internal transactions. import accounts from desktop to dedup/migrate

### PR DESCRIPTION
**Pull request by gre**
Rework the import from accounts logic in order to also migrate and dedup the accounts when LIBCORE_EXPERIMENTAL is on and when old ethereumjs account are on mobile.

What is expected here?

- Exporting from desktop works with libcore accounts too but if mobile don't enable yet the experimental, it will make the experimental ethereum libcore appearing under unsupported. It should also properly migrate old eth accounts.
- there will no longer be dup cases. (fixes LL-1716 LL-1657)
- internal transactions

### CODE REVIEW

**Comment by Arnaud97234** [comment]
**Bug found**
Accounts are not migrated but duplicated.

**How to reproduce**
- Disable Experimental Core and Node
- Import ETH accountsResults: ETH accounts from ledger.js are present (without related ERC20)
- Enable Experimental Core and Node
- Import ETH AccountsResults: ETH accounts are present twice (without related ERC20 and with related ERC20 (from libcore))

**Comment by gre** [comment]
@Arnaud97234 are you testing with LL that is also on the latest live-common?

**Comment by gre** [comment]
dedup support for import accounts with device => https://ledgerhq.atlassian.net/browse/LL-1726

support for seeing the internal ops in operation detail => done

**Comment by gre** [comment]
we'll have to fix LL-1726 before going to prod. good for merge for now.

**Pull request merged**
