### PR TITLE
LL-5273 Allow access to swap feature without the device wall

### PR DESCRIPTION
**Pull request by juan-cortes**
When accessing the swap feature we currently require users to have the exchange app installed and up to date and when inside the form we limit the selectors depending on whether they have the applications installed or not. This means we are capping the feature before users can access it. This feature allows the user to enter the swap form and request a form without knowing that they need the exchange app and, once the inline install is no longer experimental, they will be able to fulfill that requirement without leaving the form.

### Type
Feature

### Context
https://ledgerhq.atlassian.net/browse/LL-5273

### Parts of the app affected / Test plan
- Without experimental inline install, try cases with/without all required apps/accounts
- With experimental inline install, try cases with/without all required apps/accounts

### CODE REVIEW

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
@juan-cortes Metro bundler throw an error when buiding the application.
image (1)

**Comment by juan-cortes** [comment]
Ready when you are, @Arnaud97234

**Review by JunichiSugiura — DISMISSED** [review]

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
On Android everything is OK.

On iOS, After selecting the device (summary step):
- If all required app are present on the device: The drawer asking the user to open the exchange app is missing. After opening the exchange app, I can confirm the swap on the device but nothing is displayed in LL.
- If some app are missing on the device nothing happen. We stay on the swap summary.

**Expected**
expected_swap

**Actual**
actual_Swap

**Comment by juan-cortes** [comment]
iOS, I've slowly developed a hatred towards you, deep, rooted, and unavoidable.

**Review by valpinkman — DISMISSED** [review]

**Comment by juan-cortes** [comment]
I can't currently test due to the super high limits on swap, I'll test tomorrow again

**Comment by juan-cortes** [comment]
There is a limitation on react-native-modal, we bumped into this in the past but I must've forgotten about it. We need to wait for one modal to close completely before we can open another one. This is only affecting iOS, hence the bug found by @Arnaud97234 and I left a note so we don't delete that code. In any case, it should be ready for QA now, and I guess also a new dev review @valpinkman since I had to add some things. :sorry:

**Comment by juan-cortes** [comment]
Very strange that this is a new bug, are there any bugs without experimental install? To me it's two different things, this would be a bug on inline install, which is still experimental :thinking:

**Comment by juan-cortes** [comment]
With the latest version any error would close the bottom modal and kill the flow, this is to bypass the fact that we can't lock/unlock in the middle of an action, the current version leaves the user stuck when there's an error and they have no way out. This incidentally fixes that case too.

I believe this should also fix the bug that you were experiencing @Arnaud97234 let me know if you have time to check it.

**Review by Arnaud97234 — APPROVED** [review]
Tested on iOS and Android.
Tested with Floating and fixed rates.
good to merge ✅

**Review by gre — APPROVED** [review]

**Pull request merged**
