### PR TITLE
Live common 19.7.x

### PR DESCRIPTION
**Pull request by gre**
mid-sprint release of live-common & libs upgrade.

The live-common upgrades includes:

- https://github.com/LedgerHQ/ledger-live-common/releases/tag/v19.7.0
- fixes #1661 LL-2542 Portfolio V2 & all time range support
- fixes https://github.com/LedgerHQ/ledger-live-mobile/pull/1679

### CODE REVIEW

**Comment by gre** [comment]
@JunichiSugiura let's try to test this ourself a bit tomorrow before sending to QA.

**Review by JunichiSugiura — DISMISSED** [review]

**Comment by gre** [comment]
We removed this from this PR { LL-4389 includes work of https://github.com/LedgerHQ/lib-ledger-core-react-native-bindings/pull/74 via https://github.com/LedgerHQ/lib-ledger-core-react-native-bindings/pull/84 }

**Review by Arnaud97234 — DISMISSED** [review]
@gre Fo me it's a GO, I'm waiting for @nabil-brn to confirm as well and we can merge.

**Review by valpinkman — DISMISSED** [review]

**Review by valpinkman — DISMISSED** [review]

**Comment by Arnaud97234** [comment]
@gre Blank space missing, should be "10 sat/byte" instead of "10sat/byte"
IMG_F3A06EE17AD3-1

**Review by nabil-brn — APPROVED** [review]

**Pull request merged**
