### PR TITLE
Update live-common

### PR DESCRIPTION
**Pull request by gre**
https://ledgerhq.atlassian.net/browse/LL-6308

https://github.com/LedgerHQ/ledger-live-common/releases/tag/v20.2.0
https://github.com/LedgerHQ/ledger-live-common/releases/tag/v20.3.0

see https://github.com/LedgerHQ/ledger-live-desktop/pull/3962 for impact of the scope

### CODE REVIEW

**Review by valpinkman — APPROVED** [review]

**Comment by stual-ledger** [comment]
Hey there, upon trying to build this PR on Android, I ran into a syntax error in node_modules/pdkdf, let me know if you need additional details, can't provide a screenshot here @gre

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
Hey @gre, please find below, i got an issue of build as:

- ios Simulator iphone 11 ios 14.5
Screenshot 2021-07-12 at 16 27 46

**Comment by gre** [comment]
ok i think i had it one once, but i had it fixed by running with node 14
are you sure you are fully on node 14?
i had it once and then i made sure to confirm my "nvm" and it fixed it
i think it happens if you yarn with node 12 and then go node 14.

**Review by ychen-ledger — COMMENTED** [review]
I'm sorry it seems not the same case, we reproduced on node 14😔

**Comment by gre** [comment]
thanks! we are on it.

**Comment by valpinkman** [comment]
Link for context
- https://github.com/crypto-browserify/pbkdf2/issues/96
- https://github.com/tradle/rn-nodeify/issues/102

**Review by valpinkman — DISMISSED** [review]

**Comment by stual-ledger** [comment]
Hey guys,

Ran into something dirty while performing regression testing.

Steps to reproduce :
================

* Perform a successful swap via Paraswap
* Go to History > Select the last swap
-> see screenshots below

Screenshot_20210713-095039
Screenshot_20210713-095047
Screenshot_20210713-094931

**Review by ychen-ledger — COMMENTED** [review]
Can be reproduced on iphone 6s plus ios 14.6

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
It seems a Bug related to ERC-20, please have a check about it😔

**Review by valpinkman — DISMISSED** [review]

**Review by stual-ledger — DISMISSED** [review]
LGTM 🚀

**Pull request merged**
