### PR TITLE
Mashup 2021 feb 16

### PR DESCRIPTION
**Pull request by gre**
This contains all ongoing PR for 2.23:

- [ ] LL-2259 Wording: sync error wording update + link added to error banner  #1176 opened on 10 Mar 2020 by @LFBarreto 
- [ ] LL-4432 Terms localized  #1558 opened 21 days ago by @LFBarreto
- [x] LL-4429 remove sub accounts for ethereum classic  #1559 opened 21 days ago by @machard
- [x] COIN-1349 Update one support link for Polkadot  #1592 opened 4 days ago by @haammar-ledger
- [x] LL-4575 Android nav bar color themed  #1590 opened 6 days ago by @LFBarreto
- [ ] LL-4517 Analytics and event issues #1589 opened 6 days ago by @LFBarreto
- [ ] LL-4396 (Onboarding): fix button tap styling  #1588 opened 6 days ago by @LFBarreto
- [ ] [LL-4543] dot: remove transfer amount in op list  #1587 opened 7 days ago by @henri-ly
- [ ] [COIN-464] Add note in the first bond info #1585 opened 7 days ago by @henri-ly
- [ ] Coin 1146 network fees validate device #1581 opened 7 days ago by @henri-ly 
- [ ] SENTRY - fix sentry crash #1582 opened 7 days ago by @machard
- [ ] LL-4293 fix typo on onboarding  #1584 opened 7 days ago by @valpinkman
- [ ] Align isConfirmed in mobile and desktop #1535 @henri-ly 
- [ ] [LL-4543]: https://ledgerhq.atlassian.net/browse/LL-4543
- [ ] [COIN-464]: https://ledgerhq.atlassian.net/browse/COIN-464

### CODE REVIEW

**Review by nabil-brn — COMMENTED** [review]
- [x] LL-2259 Wording: sync error wording update + link added to error banner #1176 opened on 10 Mar 2020 by @LFBarreto
- [ ] LL-4432 Terms localized #1558 opened 21 days ago by @LFBarreto
- [x] LL-4429 remove sub accounts for ethereum classic #1559 opened 21 days ago by @machard
- [x] COIN-1349 Update one support link for Polkadot #1592 opened 4 days ago by @haammar-ledger
- [x] LL-4575 Android nav bar color themed #1590 opened 6 days ago by @LFBarreto
- [ ] LL-4517 Analytics and event issues #1589 opened 6 days ago by @LFBarreto
- [x] LL-4396 (Onboarding): fix button tap styling #1588 opened 6 days ago by @LFBarreto
- [ ] LL-4543 dot: remove transfer amount in op list #1587 opened 7 days ago by @henri-ly
- [x] COIN-464 Add note in the first bond info #1585 opened 7 days ago by @henri-ly
- [ ] Coin 1146 network fees validate device #1581 opened 7 days ago by @henri-ly
- [ ] SENTRY - fix sentry crash #1582 opened 7 days ago by @machard
- [x] LL-4293 fix typo on onboarding #1584 opened 7 days ago by @valpinkman
- [x] Align isConfirmed in mobile and desktop #1535 @henri-ly

---
e6241cac2 (HEAD -> mashup-2021-feb-16, gre/mashup-2021-feb-16) fixes bad merge

**Comment by nabil-brn** [comment]
:x: LL-4432 Terms localized #1558 opened 21 days ago by @LFBarreto
UTF-8 encoding?
Capture d’écran 2021-02-19 à 09 47 43
Capture d’écran 2021-02-19 à 09 48 48

**Comment by nabil-brn** [comment]
:x: LL-4575 Android nav bar color themed #1590 opened 6 days ago by @LFBarreto
When a drawer is displayed, the nav bar color changes
Capture d’écran 2021-02-19 à 09 55 00
Capture d’écran 2021-02-19 à 09 55 13

**Comment by gre** [comment]
good catch on these 👏

**Comment by nabil-brn** [comment]
❌  LL-4432 Terms localized #1558 opened 21 days ago by @LFBarreto

It crashes at language selection.

---
9790d6cf7 (HEAD -> mashup-2021-feb-16, gre/mashup-2021-feb-16) (Onboarding): fix locales issues

**Pull request merged**
