### PR TITLE
live-common 21.29.0

### PR DESCRIPTION
**Pull request by gre**
https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.29.0
https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.28.0
https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.27.0

### CODE REVIEW

**Review by valpinkman — APPROVED** [review]

**Review by juan-cortes — APPROVED** [review]

**Comment by gre** [comment]
HOLDing because we need a decision weither Eth app is released (whch is a new mandatory upgrade https://github.com/LedgerHQ/ledger-live-common/pull/1618/files#r787613499 ) or revert that restriction.

like https://github.com/LedgerHQ/ledger-live-desktop/pull/4663

**Comment by haammar-ledger** [comment]
Replaced with https://github.com/LedgerHQ/ledger-live-desktop/pull/4663

**Comment by gre** [comment]
it was discussed that this PR is not mergeable because NFT perf issue so we will reuse the PR and soon amend another live-common bump.

**Comment by gre** [comment]
as this PR didn't make it, replaced by https://github.com/LedgerHQ/ledger-live-mobile/pull/2169

**Pull request closed without merging**
