### PR TITLE
fix(Alert): set width 100% always - LL-5255

### PR DESCRIPTION
**Pull request by ghost**
### Type

UI Fix

### Context

On Swap, info alert is not full width, content is not visible.

Instead of wrapping all <Alert> in a <View> with width=100%, i fixed the Alert component to always have 100% width (there is no use-case were Alert does not take all available horizontal space).
I updated the SkipDeviceVerification component that used the wrapping solution.

Issue: https://ledgerhq.atlassian.net/browse/LL-5255

### Parts of the app affected / Test plan

Also, alert in SkipDeviceConfirmation after Buy verification without device should not change.

### CODE REVIEW

**Review by machard — APPROVED** [review]

**Review by juan-cortes — DISMISSED** [review]

**Comment by Arnaud97234** [comment]
@rjarasson-ledger Your fix works but by testing it I saw the same error on the confirm swap drawer. Could you fix it in the same PR or you prefer me to open a new bug task in Jira?
- Select accounts and amount
- Swap summary
- Drawer when waiting from user to confirm on device

IMG_1201

**Review by gre — DISMISSED** [review]
:go:

**Comment by rjarasson-ledger** [comment]
I tried to reproduce the issue, but unseccessfully.
On my side, on both Android and iOS, the issue was present, but fixed by this PR.
As i am not able to reach this specific screen, i added the Alert in other DeviceAction confirm drawers like Receive or Allow Manager.

**Comment by rjarasson-ledger** [comment]
@Arnaud97234 I was not able to find a specific fix to this drawer.

But https://github.com/LedgerHQ/ledger-live-mobile/pull/1700 should fix both the Error to display correctly, and the Alert component to be fixed by the current PR.

It seems like this drawer on Swap is completely buggy, and provoke those side effects.

This PR fixes the Alerts not affected by other UI glitches.

**Review by Arnaud97234 — APPROVED** [review]
To test this PR I had to pull https://github.com/LedgerHQ/ledger-live-mobile/pull/1700 in it.
Both are ok. ✅

**Pull request merged**
