### PR TITLE
LL-4447 Floating rate support for swap

### PR DESCRIPTION
**Pull request by juan-cortes**
Includes a major live-common bump to https://github.com/LedgerHQ/ledger-live-common/releases/tag/v19.0.0

### Type

Feature

### Context

https://ledgerhq.atlassian.net/browse/LL-4447

### Parts of the app affected / Test plan
Floating is now available in production and swap will automatically point to the v2 by default. No need for extra environment variables or changes in order to test it. Provider 1 apps, go.

- Test the full swap feature for both fixed and floating rates
- Test the new feature for flipping accounts `left <-> right` inside the swap form
- Test that the device running latest Exchange from provider 1 which shows different wording for floating and fixed rates. There's no need to complete a full swap for this particular test, you just need to reach the confirmation step and look at the device, it should display "get" vs "get estimated" or something along those lines.

### CODE REVIEW

**Review by gre — CHANGES_REQUESTED** [review]
```

/home/runner/work/ledger-live-mobile/ledger-live-mobile/src/reducers/settings.js
Error:   468:5  error  Assignment to function parameter 'supportedCurrencies'  no-param-reassign


```

**Comment by gre** [comment]
@juan-cortes is there a reason for this PR to still be HODL and therefore not reviewable by QA?

**Comment by juan-cortes** [comment]
> @juan-cortes is there a reason for this PR to still be HODL and therefore not reviewable by QA?

This "not reviewable" concept is something I feel it's not shared by everyone since it's been reviewed a d in close contact with qa on it. It was labeled hodl for the known reasons and I removed the flag yesterday. 

Maybe it bugged, maybe I can't remove a flag... But it's not really "not reviewable by qa"

**Comment by juan-cortes** [comment]
We were missing the changes to the summary step to show the user the breakdown of the amounts. The last commit introduces that.
image

**Review by gre — DISMISSED** [review]

**Review by gre — APPROVED** [review]

**Review by Arnaud97234 — APPROVED** [review]

**Pull request merged**
