### PR TITLE
Use Fixed rate by default instead of Floating rate

### PR DESCRIPTION
**Pull request by hzheng-ledger**
In swap screen, we should use Fixed rate by default instead of Floating rate
https://ledgerhq.atlassian.net/browse/LL-5259

### CODE REVIEW

**Review by IAmMorrow — APPROVED** [review]

**Comment by cthepot-ledger** [comment]
not it's floating rate by default. the inactive UI component should be floating rate by default as well.

**Comment by cthepot-ledger** [comment]
should not merge this

**Comment by hzheng-ledger** [comment]
@cthepot-ledger 
Hi, Chris, I just checked the mobile application UI in swap page.
Screenshot 2021-06-08 at 10 31 30

Since the "Fixed rate"/"Floating rate" selection is after the coin selection. So, the "Fixed rate"/"Floating rate" CTA is always active. I assume that nothing needs to be done for this ticket. Could you please confirm that? Thanks

**Comment by gre** [comment]
on Jira, ticket is abandoned. closing this PR unless some mistake? we can reopen if there are.

**Pull request closed without merging**
