### PR TITLE
LL3633 black friday banner

### PR DESCRIPTION
**Pull request by machard**
add back black friday banner

### Type

UI

### Context

https://ledgerhq.atlassian.net/browse/LL-3633

### Parts of the app affected / Test plan

check black friday banner. You can change the local date to check the conditional display

### CODE REVIEW

**Review by juan-cortes — APPROVED** [review]
lgtm, maybe @cthepot-ledger @aramab we should add the utm to the link, so that your analytics can know the hits on the black friday page come from the app

**Comment by gre** [comment]
@machard why is it in HODL? 
(also: conflicts)

**Review by nabil-brn — CHANGES_REQUESTED** [review]
I think we should put it as first occurence in the array, it takes 5 secs per slide, users won't reach it in the end.

---
bf05128c4 (HEAD -> LL-3633, machard/LL-3633) black friday banner

**Review by nabil-brn — APPROVED** [review]
✓ QA-ed

---
c92d5ff83 (HEAD -> LL-3633, machard/LL-3633) Merge branch 'develop' into LL-3633

**Review by gre — APPROVED** [review]

**Pull request merged**
