### PR TITLE
TAC modal onClick only on link

### PR DESCRIPTION
**Pull request by valpinkman**
Fix onClick from full text to link only in Terms and Conditions Modal

### Type

Fix

### Context

LL-3869

### CODE REVIEW

**Review by gre — APPROVED** [review]

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
### Bug found
On both Android and iOS, LLM crashes when entering Lending flow.
IMG_1054

I can't reproduce on develop branch

### How to reproduce
- Import ETH Accounts
- Tap Lending in the bottom bar

**Comment by gre** [comment]
@JunichiSugiura  / @machard  / @juan-cortes   : any of you to take over to fix this as @valpinkman  is off. thanks

**Comment by juan-cortes** [comment]
I can take it

**Comment by juan-cortes** [comment]
Current version changed the path of the link on the translated literals, should work. 
image

**Review by gre — APPROVED** [review]

**Review by nabil-brn — CHANGES_REQUESTED** [review]
There is a weird animation when I click on the checkbox.

Enregistrement de l’écran 2020-11-25 à 07 21 56

---
iOS (iPhone 11 Simulator)
dc87c5202 (grafted, HEAD -> pr/valpinkman/1458, valpinkman/fix/TAC-compound-click) Update switch label translation to fix crash

**Comment by juan-cortes** [comment]
Wtf ios

**Comment by juan-cortes** [comment]
Try again when you can @nabil-brn 😪 
Unbelievable

**Review by gre — APPROVED** [review]

**Review by nabil-brn — APPROVED** [review]
Reviewed in #1482 

---
c527903 (HEAD -> pr/gre/1482-1, gre/mashup-2020-11-27, pr/gre/1482) fixes typo

**Pull request merged**
