### PR TITLE
Ethjs enabled in production

### PR DESCRIPTION
**Pull request by gre**
- ETHjs for all
- added Experimental explorers
- reworked the gas price component to use the range provided by network (if experimental on)

### Type

update

### Context

https://github.com/LedgerHQ/ledger-live-desktop/pull/3248

https://github.com/LedgerHQ/ledger-live-common/pull/912

### Parts of the app affected / Test plan

all accounts are migrated to ETHjs.
gas price works and you can do ETH/ERC20 tx without an issue.

### CODE REVIEW

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
Drag down on Portfolio screen should trigger Sync.
Works properly on Accounts and Account screens.

**Comment by juan-cortes** [comment]
I'm taking a look

**Comment by juan-cortes** [comment]
So, it seems that we introduced this regression on https://github.com/LedgerHQ/ledger-live-mobile/pull/1423 where we wrapped the list of dashboard for performance, but we didn't move the pull to refresh to the wrapping list. This should fix that.

**Comment by gre** [comment]
@nabil-brn can you take over? Thanks

**Review by nabil-brn — CHANGES_REQUESTED** [review]
_Receive_ is broken on all currencies, starting the flow from the account itself.

---
4544da2e6 (HEAD, gre/ethjs-prod) Fix regression in pull to refresh - dashboard

**Review by nabil-brn — CHANGES_REQUESTED** [review]
Sending ERC20 displays a _Confirmed_ status instantly after clicking on operation details.

---
e76b633bf (HEAD, gre/ethjs-prod) Merge branch 'develop' into ethjs-prod

**Comment by juan-cortes** [comment]
> _Receive_ is broken on all currencies, starting the flow from the account itself.
> 
> [4544da2](https://github.com/LedgerHQ/ledger-live-mobile/commit/4544da2e678bdda914d4b12b569c4685dc0a58c6) (HEAD, gre/ethjs-prod) Fix regression in pull to refresh - dashboard

This is no longer the case according to my testing, can you verify on latest @nabil-brn ?

**Comment by juan-cortes** [comment]
> Sending ERC20 displays a _Confirmed_ status instantly after clicking on operation details.

Should be addressed in the latest commit, please check @nabil-brn

**Review by nabil-brn — APPROVED** [review]
No remaining issues spotted ✓

**Pull request merged**
