### PR TITLE
LL-5939 Add export logs to settings/help

### PR DESCRIPTION
**Pull request by juan-cortes**
Add a CTA to be able to export logs on the Help section of the settings screens. Also, we took the time to refactor the export logic into a reusable hook since we are using it in three different places. Fixed the debug screen that was triggering an alert for some reason, the see latest logs CTA should now work as expected.
image

### Type

Feature

### Context

https://ledgerhq.atlassian.net/browse/LL-5939

### Parts of the app affected / Test plan

- Test that the error screens still export the logs correctly (can be a `deviceAction` error, or any other error with logs)
- Test that the export logs feature from the settings/help screen works
- On Android, make sure the naming is good, iOS will still have the "file" name

### CODE REVIEW

**Review by achabrolin-ledger — APPROVED** [review]

**Comment by juan-cortes** [comment]
Closed by https://github.com/LedgerHQ/ledger-live-mobile/pull/1839 merging it (cc. @gre)

**Review by gre — APPROVED** [review]

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
Please find the feature export logs is missing in the error screens 

Steps to reproduce: 
1. Open App and add two accounts for ETH.
2. Get the receive address of one account.
3. Perform send flow for the Eth account
4. Click reject in your device at the last step(Review transaction on your device)

Expected result: 
The error screens still export the logs correctly

Actual Result: 
The feature export logs is missing in the error screens, please see the result as attached video
https://user-images.githubusercontent.com/85551245/129374188-f08bce63-f88f-4ced-b0ff-077cf13f3fe0.MP4

**Comment by juan-cortes** [comment]
I don't think _all error_ screens should have export logs CTA @ychen-ledger what you are describing is a user reject scenario, not an error. Perhaps to try you could use the wrong device on a receive flow, I think that error (wrong seed for an account) should have the cta.

**Review by ychen-ledger — COMMENTED** [review]
@juan-cortes, i agree. I compared with prod have export logs feature, that's why I put a request for a reject scenario. I'll dig more for the error page and give your feedback.

@juan-cortes here are my feedback for dig in the error page: 

- We don't have the export logs feature for the case _use the wrong device on a receive flow_ , please see the result below: 

https://user-images.githubusercontent.com/85551245/129590680-8cd52ace-cce0-493f-8d31-7ab233b2e3ed.MP4

- With the case, Bluetooth is cut off or internet is cut off during add account, we all have a personalized error page( please confirm export logs feature is needed here) please check the result as below: 

https://user-images.githubusercontent.com/85551245/129590927-78e69eae-d386-4d74-b71e-8a3cdd74ca58.MP4


IMG_0098

**Comment by juan-cortes** [comment]
@ychen-ledger It's not up to me to decide whether what you are reporting is a bug or not, the scope of the task was to add the export cta to the settings/help menu. If the export logs is missing on some error screens, we should file a bug and let product/core prioritise the fix or not fix (cc @gre)

**Review by ychen-ledger — COMMENTED** [review]
@juan-cortes ,Thanks for clear up, i'll check with @cthepot-ledger. Btw, FYI, all error screens missing export logs i listed in the comment is just in this branch, not in production

**Comment by juan-cortes** [comment]
> @juan-cortes ,Thanks for clear up, i'll check with @cthepot-ledger. Btw, FYI, all error screens missing export logs i listed in the comment is just in this branch, not in production

In that case, then I probably broke the logic from the Pure component when converting it, and you are correct in your findings. Let me get back to you and you can try again to see if they are aligned with develop, sorry for the confusion @ychen-ledger

**Comment by ychen-ledger** [comment]
> > @juan-cortes ,Thanks for clear up, i'll check with @cthepot-ledger. Btw, FYI, all error screens missing export logs i listed in the comment is just in this branch, not in production
> 
> In that case, then I probably broke the logic from the Pure component when converting it, and you are correct in your findings. Let me get back to you and you can try again to see if they are aligned with develop, sorry for the confusion @ychen-ledger

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
hey @juan-cortes ,  the export logs is broken for iOS side but works well in the Android side, it may cause of merge in develop, please check the result as below:

- For iOS

https://user-images.githubusercontent.com/85551245/129710952-09ab5077-ef41-435a-b6a7-99ac98f047d0.MP4

- For Android: 

https://user-images.githubusercontent.com/85551245/129711133-26890a0f-9070-4e9b-98bb-658f25278e1d.mp4

**Comment by juan-cortes** [comment]
@ychen-ledger I'm taking a look now, you confirm it works on develop but not on this PR?

**Comment by ychen-ledger** [comment]
> @ychen-ledger I'm taking a look now, you confirm it works on develop but not on this PR?

all testing are in this branch 🙂

**Review by ychen-ledger — APPROVED** [review]
Validated with: 

- iOS 14.6
- Ledger live 2.32.0
- Android version 10

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
