### PR TITLE
LL-7232 update icon resources

### PR DESCRIPTION
**Pull request by LFBarreto**
Updated icon resources for splashscreen and app icons + loader on app boot

### Type

Feature
### Context

[LL-7232]
### Parts of the app affected / Test plan

[LL-7232]: https://ledgerhq.atlassian.net/browse/LL-7232

### CODE REVIEW

**Comment by juan-cortes** [comment]
Testing iOS for you since apple doesn't want you to do it on linux, this is how the splash and the icons look (that floating thing is the home button so you don't break the hardware one, nothing to do with us). I believe the icon on settings About should also use the new icon though.

Screenshot 2021-09-16 at 12 00 47

**Comment by juan-cortes** [comment]
I updated some icon and colors after syncing with design, to me it's ready to QA

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
Hi @juan-cortes , please find below(only for iOS)

- the App launched with a old logo flash at first
- for the flash animation, the process of logo becoming big is missing 
Please see the result as below: 

https://user-images.githubusercontent.com/85551245/135229731-326e290a-f12e-4fe6-802e-47abc9dad5c1.MP4

**Comment by juan-cortes** [comment]
Oh no, that's so ugly @ychen-ledger why did you do that!

**Comment by ychen-ledger** [comment]
> Oh no, that's so ugly @ychen-ledger why did you do that!

it happened just as it was, sorry🥶

**Comment by juan-cortes** [comment]
> > Oh no, that's so ugly @ychen-ledger why did you do that!
> 
> it happened just as it was, sorry🥶

I know, I was just teasing. I'm taking a look now

**Comment by juan-cortes** [comment]
Can you take a look again @ychen-ledger ?
It's in theory a cache issue and renaming the assets should remove this first ghost old logo splash, but I can't test on a staging build myself. From what I see, it just goes black and then we have the animated logo thing 🤷🏼

**Comment by ychen-ledger** [comment]
> Can you take a look again @ychen-ledger ? It's in theory a cache issue and renaming the assets should remove this first ghost old logo splash, but I can't test on a staging build myself. From what I see, it just goes black and then we have the animated logo thing 🤷🏼

@juan-cortes Thanks a lot, i'll do a double check🙈

**Review by ychen-ledger — DISMISSED** [review]
Sorry, friend 🤦🏼‍♀️ @juan-cortes, it still not works on iOS side🥶 !!! As you can't build on ios, we will asked @achabrolin-ledger to do a fix with build locally. Please find below, the app launched with a blank page, please see the result as below: 


https://user-images.githubusercontent.com/85551245/136064648-fed38f42-a39c-4119-80c9-30a77b53ff66.MP4

**Review by valpinkman — DISMISSED** [review]

**Review by valpinkman — DISMISSED** [review]

**Review by nparigi-ledger — DISMISSED** [review]

**Review by ychen-ledger — DISMISSED** [review]
Agreed with @LFBarreto @Arnaud97234, we want to merge this PR first and testing on iOS once we able to build on iOS or in pre-release
Validated Android with: LLM 2.34.4/Android 11

**Review by ychen-ledger — APPROVED** [review]
Validated with: 

- LLM 2.34.4
- Android 11/ iOS 14.7.1
- A UI bug will be fixed in https://ledgerhq.atlassian.net/browse/LL-8139

**Comment by qd-qd** [comment]
🚀

**Pull request merged**
