### PR TITLE
don't show scrollbar in Portfolio

### PR DESCRIPTION
**Pull request by gre**
because makes no sense in infinite scroll

### CODE REVIEW

**Comment by gre** [comment]
to me it is a bug when i see this. on mobile i see no app showing you indicator when the list will grow, it always feel like the app isn't finished

**Comment by meriadec** [comment]
it's the case for many messaging app (WhatsApp, Telegram, etc.) bcause they don't show you the entire message list unless you scroll (seems that is exact same behaviour as txs list), and when you scroll, the scrollbar thumb size changes.

even google mobile (with "Show more") works like that (I mean: displaying scrollbar)

IMO it's accessibility stuff, not a fan of hiding this subtle info (we do it on desktop and this is bad)

**Comment by MortalKastor** [comment]
I can't think of any app hiding the scrollbar on infinite load 🤔
From what I see, popular apps based on a huge infinite list (I checked Twitter, Instagram and Tumblr) show the scrollbar.

**Comment by gre** [comment]
ok, we can show it back i guess then!

**Pull request merged**
