### PR TITLE
LL-6458  Onboarding seed warning improvement

### PR DESCRIPTION
**Pull request by juan-cortes**
Rework the onboarding warning for users that might be conned into using a supplied seed instead of a generated one, it removes the warning boxes from the onboarding UI and instead replaces them with a new bottom modal that shows the warning itself. Only for the "already initialized" and the "I have a recovery seed" cases on the onboarding.

### Type

Feature

### Context

https://ledgerhq.atlassian.net/browse/LL-6458

### Parts of the app affected / Test plan

- Reach the onboarding with any device selection
- Go over the different use cases
- If the case is "Connect your nano" or "Restore a recover seed" (or whatever the wording is) there should be modal popping up when we click on the option.
- Make sure other options don't show this modal
- Make sure the modal can be closed and the contact support cta works.

### CODE REVIEW

**Review by LFBarreto — DISMISSED** [review]

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
Hey @juan-cortes , please find below

- We have a warning drawer in the step of **pair your Nano**  during the flow **Restore your recovery phrase on a new device**, please see the result as the video below: 

https://user-images.githubusercontent.com/85551245/133122396-edce52e8-f651-4e3a-adcc-13cda7116ded.mp4

- The performance on iOS is not good, but it do works well on Android👀 (iOS version 14.6/ledger live 2.33.0)

https://user-images.githubusercontent.com/85551245/133123271-1d9f2951-4aa2-44d8-9f86-bf9fceca6e38.MP4

**Comment by juan-cortes** [comment]
Thanks @ychen-ledger I'll take a look tomorrow for the double modal. I'm surprised about the ios performance since this should have zero impact on that part 🤔

**Comment by juan-cortes** [comment]
@ychen-ledger The current version should have the double alert bug solved.

**Review by ychen-ledger — DISMISSED** [review]
Validated with: 

- Ledger live 2.33.0
- iOS 14.8 
- Android 10
- LNS/ LNX/Blue

**Review by LFBarreto — DISMISSED** [review]

**Comment by valpinkman** [comment]
Since this is onboarding related and I can see an issue in the e2e test related to onboarding, I guess this PR needs to update the detox test

**Review by valpinkman — CHANGES_REQUESTED** [review]
Detox test to be updated

**Comment by juan-cortes** [comment]
Detox has been updated @valpinkman :beau:

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
