### PR TITLE
LL-1184 Pixel push mobile 2

### PR DESCRIPTION
**Pull request by juan-cortes**
image

- Removed the small add button and replaced it with the old full row one
- Replaced "Connect" with "Select", on Manager
- I can't get the ellipsis to be blurry @gre @aramab , lgtm
- Increased the size of the illustration to pair a new nano X

### CODE REVIEW

**Comment by gre** [comment]
In term of wording, I would not use the word "Pair". Maybe just "new Ledger Nano X" ?

**Comment by juan-cortes** [comment]
> In term of wording, I would not use the word "Pair". Maybe just "new Ledger Nano X" ?

If you are sure, I'll change it. Should we invoke the word genie?  @dasilvarosa

**Comment by gre** [comment]
can you 

```
    "deviceNotFoundPairNewDevice": "Add new Ledger Nano X",
```

?

**Comment by juan-cortes** [comment]
Done @gre

**Pull request merged**
