### PR TITLE
LL-2842 Deep Link

### PR DESCRIPTION
**Pull request by LFBarreto**
(DeepLink): add deep link support for the app -> check ReadMe for more details

### Type

Feature

### Context

LL-2842

### Parts of the app affected / Test plan

Install the app
then for Android run

```
  adb shell am start -W -a android.intent.action.VIEW -d "ledgerlive://{{YOUR_URL}}" com.ledger.live.debug
```
(use com.ledger.live.staging for staging build)

on IOS run 

```
xcrun simctl openurl booted ledgerlive://{{YOUR_URL}}
```

It should redirect to the correct page 

**Deep Linking Test Page App**

to run it 
```
yarn run test-deep-links
```

IMG_20200727_145214

### CODE REVIEW

**Comment by gre** [comment]
AFAIK for iOS, we need to do something special (there is nothing to do for Android? curious) in Obj C to enable the deep link feature.

**Comment by gre** [comment]
conflicts

**Comment by gre** [comment]
receive

**Comment by nabil-brn** [comment]
> Solution not found, it probably needs a rework of the navigation stack which is a bit out of scope here.
Well we can merge it, no issue is remaining.

**Pull request merged**
