### PR TITLE
LL-968 Allow user to finish onboarding with an empty import

### PR DESCRIPTION
**Pull request by juan-cortes**
This ads the posibility to retry after scanning the LiveQR Code from desktop or to import simply the settings in the case of not having accounts to import. It initially didn't have the retry cta, hence the comments below mentioning the need to reword.

image

### CODE REVIEW

**Comment by khalilbenihoud** [comment]
We should reword it since we don't really give the users the possibility to try again. @aramab

**Comment by aramab** [comment]
@khalilbenihoud 
See link in the design issue for wording and retry button : https://ledgerhq.atlassian.net/browse/LL-969?focusedCommentId=23317&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23317

**Comment by juan-cortes** [comment]
Do we keep this one on hold until @khalilbenihoud finishes the sandbox?

**Comment by khalilbenihoud** [comment]
@juan-cortes  - @bscholving is going to take care of it.

**Comment by juan-cortes** [comment]
great!

**Comment by juan-cortes** [comment]
@gre @Arnaud97234 @khalilbenihoud This is ready for testing now, I've updated the first message with the new screenshot

**Comment by juan-cortes** [comment]
@Arnaud97234 nice catch, I'm guessing it _should_ be exportable, we could make it exportable, but do we care enough to do it? @gre

**Comment by gre** [comment]
Yes, let's export Developer Mode settings as well, it makes sense because it is somewhat consistent with account you imports. If you import only Testnet account, then later you go to Manager, you don't see Testnet app.

so let's import it, however @Arnaud97234  please don't consider it blocking this PR. Because to actually fix this, we first need to provide a fix in desktop project (it doesn't export this info) and then we can also do a new PR on mobile.

the fix is also to be done in live-common btw @juan-cortes  , look at `src/cross.js`

**Pull request merged**
