### PR TITLE
LL-4532 Remove backup pack banner

### PR DESCRIPTION
**Pull request by juan-cortes**
### Type

Feature

### Context

https://ledgerhq.atlassian.net/browse/LL-4532

### Parts of the app affected / Test plan

- Open the app
- Make sure the banner is not present

### CODE REVIEW

**Review by LFBarreto — APPROVED** [review]

**Review by gre — CHANGES_REQUESTED** [review]
@juan-cortes is there a reason why we are not removing the code here? If these are not coming again in future, there is no reason why we are commenting. we should just delete all of these.

In this particular case the banner will come back once there's stock if I understood correctly what @cthepot-ledger said, so it made sense to just comment it out. There seem to be other banners commented out, I'm all up for deleting them, and the associated files, and recovering them from git if needed in the future

**Review by gre — APPROVED** [review]
ok

**Comment by juan-cortes** [comment]
> @juan-cortes is there a reason why we are not removing the code here? If these are not coming again in future, there is no reason why we are commenting. we should just delete all of these.



In this particular case the banner will come back once there's stock if I understood correctly what @cthepot-ledger said, so it made sense to just comment it out. There seem to be other banners commented out, I'm all up for deleting them, and the associated files, and recovering them from git if needed in the future

**Review by nabil-brn — APPROVED** [review]
✓ QA-ed

---
45148026f (HEAD -> LL-4532, juan/LL-4532) LL-4532 Remove backup pack banner

**Pull request merged**
