### PR TITLE
Reenable basic Flipper config on iOS

### PR DESCRIPTION
**Pull request by OlivierFreyssinet**
Flipper is the debugging tool developed by facebook to debug React Native apps.

We were already using it and it's currently enabled on Android but it was recently disabled on iOS as it was causing build issues (I checked with @JunichiSugiura if there was any other particular reason to disable it): https://github.com/LedgerHQ/ledger-live-mobile/pull/1953 https://github.com/LedgerHQ/ledger-live-mobile/commit/765ece1aa9c3494adb1fcc287ea2641893e02978

I used the default config provided [here](https://fbflipper.com/docs/getting-started/react-native-ios/#initialization) to build iOS and it seemingly builds and runs fine as you can see on the following video: the plugins that are not in the "react native" section, such as the network plugin require this configuration to work.

https://user-images.githubusercontent.com/91890529/152189617-02665955-276f-42ff-a6af-0081fac17f41.mov

### Type

Debugging experience improvement

### Context

I wanted to access the network tool to debug something on the market page for #2111

### CODE REVIEW

**Review by valpinkman — CHANGES_REQUESTED** [review]
Podfile.lock needs to be update

`yarn pod`

**Comment by ofreyssinet-ledger** [comment]
Ok so I don't get a diff after running `yarn pod`...
I tried on a freshly cloned repo and I tried a hard clean with [`npx react-native-clean-project`](https://github.com/pmadruga/react-native-clean-project)
Here's my config:
```
% npx react-native info        
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 1.66 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Review by LFBarreto — APPROVED** [review]

**Comment by ofreyssinet-ledger** [comment]
@valpinkman it's building properly now since @elbywan's last commit https://github.com/LedgerHQ/ledger-live-mobile/pull/2165/commits/170d3b8d758eff287bcc6c002e0283544474c836
cf. this run https://github.com/LedgerHQ/ledger-live-build/runs/5063971797?check_suite_focus=true#step:2:462

**Comment by valpinkman** [comment]
@ofreyssinet-ledger good that it builds now. If you can rebase and pass the CI, it's a go from me

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
