### PR TITLE
LL-5048 - fix(Polkadot): simpleOperation info optionnal + update to Alert

### PR DESCRIPTION
**Pull request by ghost**
### Type

UI Polish

### Context

For Polkadot, on Withdraw modal, the description and the info are redundant.
So we can make info optionnal by not having a translation key for it.

Upgraded the info with an Alert.

### Parts of the app affected / Test plan

On a Polkadot account with staking and available withdrawable unbonded amount (28 days after unbonded):
- [...] > withdraw unbonded
- modal should only contain a description
- close modal
- [...] > clear nominations
- chill modal should have both description and an info

Info should now fit the design system.

### CODE REVIEW

**Comment by rjarasson-ledger** [comment]
Wait for https://github.com/LedgerHQ/ledger-live-mobile/pull/1675 to be merge to QA because currently, the fix is still impacted by a previous reported bug:

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
- Withdraw unbonded is OK 🟢 
- Clear Nomination drawer: the infobox is empty 🔴 
clearNominationDrawer

**Comment by rjarasson-ledger** [comment]
@Arnaud97234 I rebased and fixed the width issue (still an issue with inheriting width from parent on android, a bit annoying).

Should be good now.
Sorry for having forgotten this ticket, thanks !

**Review by Arnaud97234 — APPROVED** [review]

**Review by Arnaud97234 — DISMISSED** [review]
I rebased locally, everything is ok.
Once @rjarasson-ledger as rebased, please review (Dev + Core) then it can be merged without waiting for QA to review once again. 🙏 
✅

**Review by Arnaud97234 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
