### PR TITLE
Fix debug screens + drop unused + Improvements to Debug Store

### PR DESCRIPTION
**Pull request by juan-cortes**
Screenshot 2020-08-08 at 18 21 07

Screenshot 2020-08-08 at 17 54 20

image

- Killed the export accounts over websocket experimental, it was an experiment I did back in 2019 and it didn't go anywhere, we can always recover it if we wanted to in the future.
- Killed the debug SVG feature, same.
- Fixed the DebugBLE screen UI, there were some invisible buttons and broken UI.
- Fixed the DebugBLE Benchmarking screen, now it's accessible from the DebugBLE header.
- Added a trigger to debug the whole app state from the browser
- Added a way to edit the app state from the browser for easier debugging and qa.

### CODE REVIEW

**Review by gre — DISMISSED** [review]

**Comment by juan-cortes** [comment]
This is in fact a really nice thing that is now outdated, sad times

**Comment by gre** [comment]
why is it outdated?

**Comment by juan-cortes** [comment]
I mean it's a month old already

**Comment by gre** [comment]
It doesn't pass CI / lint at the moment so not mergeable. Can you fix and merge develop? thanks

**Comment by juan-cortes** [comment]
It should now @gre

**Pull request merged**
