### PR TITLE
LL-5334 Market page

### PR DESCRIPTION
**Pull request by LFBarreto**
integrate new market page feature

Edit (@ofreyssinet-ledger): on iOS for some reason it's necessary to run `cd ios && pod install` to get Reanimated 2 to work & not crash upon opening the market page

<details>
<summary>Edit 31/01 (@ofreyssinet-ledger): dusk theme removal & rebranding primary colors </summary>
https://ledgerhq.atlassian.net/browse/LIVE-621
- Removed `dusk` theme (for existing users with fallback to `dark`)
- Replaced "live blue"  by the rebranding purple
- Make it work on iOS (pods etc.)

https://user-images.githubusercontent.com/91890529/151822738-b18e01b5-c913-402f-8bc4-34e8d1366221.mp4

</details>

### Type

 Feature

### Context
 [LL-5334]

### Parts of the app affected / Test plan

[LL-5334]: https://ledgerhq.atlassian.net/browse/LL-5334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ofreyssinet-ledger** [comment]
Weird issue, not sure if linked to LLM or LLC implementation, I'm going to look into it now but just posting here to keep a track of it.

When refreshing the data sometimes, `marketData` comes back unordered (for instance starting from rank 41 to 60 and then back to rank 1 (cf. 1st video) then at the bottom it's impossible to trigger the "load more" (cf. 2nd video)

https://user-images.githubusercontent.com/91890529/152013833-ac882ac1-c65b-4264-81f3-44baea8d55c2.mp4


https://user-images.githubusercontent.com/91890529/152016202-ab39863b-fd2b-4e7c-ab09-18b860c4a9b5.mp4

**Comment by ofreyssinet-ledger** [comment]
When filtering "live supported apps" and sorting by "Rank (market cap) asc." the last currencies in the list are not the ones expected (bitcoin ethereum etc.):

https://user-images.githubusercontent.com/91890529/152325469-368029b1-2f5b-4139-945a-5f54f27d5526.mp4

**Comment by ofreyssinet-ledger** [comment]
**Bug with the "starred coins" filter:**
In the following video the only starred coin I have is Bitcoin.
1. Toggle the "starred" filter to `true`
2. Toggle the "view" filter to "live compatible"
3.  **First issue**: all coins are now displayed even though the "starred" filter is still enabled.
4. Toggle the "view" filter to "all coins"
5. **Second issue**: now only the starred coin is visible but the `loading` state is on so the footer appears with a loading indicator.

https://user-images.githubusercontent.com/91890529/152326644-0a7b4fd9-4b29-4a45-905d-b84ea93127e2.mp4

**Comment by ofreyssinet-ledger** [comment]
The UI lib will need to be updated for some fixes:

https://github.com/LedgerHQ/ui/pull/168
https://github.com/LedgerHQ/ui/pull/169

**Review by thomasrogerlux — APPROVED** [review]

**Review by valpinkman — APPROVED** [review]

**Comment by ofreyssinet-ledger** [comment]
Feedback from QA (@nabil-brn)
- [ ] no wifi -> empty state missing
- [ ] sort/time/currency filters UX -> remove bouton apply
- [ ] currency filter empty state -> style is missing
- [ ] currency value not refreshed when selecting different currency -> check dependencies/memo etc.
- [ ] time range change -> percentage value not updating properly, weird dependency between main list & graph
- [ ] search -> trim leading/trailing spaces from request
- [ ] don't display footer when data list empty & loading ?
- [ ] buy -> add account -> no redirect (I don't know if that is possible)
- [ ] swap -> no autofill of "from" field **I don't think that is possible**
- [ ] swap -> no account -> should redirect to add account instead of swap if no account
- [ ] bookmark filter not disablable if no currency is bookmarked
- [x] “your holdings” -> remove this section for now

**Pull request merged**
