### PR TITLE
Upgrade React Native to 0.67.3

### PR DESCRIPTION
**Pull request by OlivierFreyssinet**
Upgraded RN from 0.65.1 to 0.67.3 (latest stable) by following the [upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.65.1&to=0.67.3).

The [full React Native changelog is here](https://github.com/facebook/react-native/blob/main/CHANGELOG.md) and I didn't detect any breaking change that could affect LLM.

Also includes these changes regarding dependencies:

- Upgraded react-native-reanimated to latest stable (checked the changelog, no breaking change)
- Upgraded react-native-modal to latest stable (checked the changelog, no breaking change)
- Removed unused react-native-pager-view

### Type

Dependency upgrade

### Context

[LIVE-894]

### Parts of the app affected / Test plan

I have to test these things which could break in a RN upgrade according to @nabil-brn:

**iOS:**
- [x] QR code scan (camera)
- [x] Password lock
- [x] Passwordlock with fingerprint
- [x] Deeplinks (e.g. walletconnect)
- [x] Webviews (discover)

**Android:**
- [x] QR code scan (camera)
- [x] Password lock
- [x] Passwordlock with fingerprint
- [x] Deeplinks (e.g. walletconnect)
- [x] Webviews (discover)

[LIVE-894]: https://ledgerhq.atlassian.net/browse/LIVE-894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nabil-brn — CHANGES_REQUESTED** [review]
I can't build an android staging app

```
> Task :app:processStagingReleaseGoogleServices FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ‘:app:processStagingReleaseGoogleServices’.
> No matching client found for package name ‘com.ledger.live.staging’
```

---
a556d0f6d (HEAD -> upgrade-rn-0.67.2, ledger/upgrade-rn-0.67.2) Revert flowconfig flow version change

**Comment by ofreyssinet-ledger** [comment]
@nabil-brn 
> I can't build an android staging app

-> that's fixed on develop, I need to rebase

**Review by nabil-brn — APPROVED** [review]
⚠️ DO NOT MERGE before the mobile pre-release.
✔️ Tested on iOS & Android

---
ab80d4de9 (HEAD -> upgrade-rn-0.67.2, ledger/upgrade-rn-0.67.2) Revert flowconfig flow version change

**Comment by nabil-brn** [comment]
Given https://github.com/LedgerHQ/ledger-live-mobile/tree/release/2.39.0 exists, I can merge 👀 .

**Review by thomasrogerlux — APPROVED** [review]

**Pull request merged**
