### PR TITLE
fix delegation counter value for tezos

### PR DESCRIPTION
**Pull request by hzheng-ledger**
Fix https://ledgerhq.atlassian.net/browse/LL-5208
the counter value was wrong before because the tezos price was calculated based on the delegation operation date

### CODE REVIEW

**Review by valpinkman — CHANGES_REQUESTED** [review]
you can just use `new Date()`

**Comment by hzheng-ledger** [comment]
> you can just use `new Date()`

Fixed. thanks

**Review by gre — CHANGES_REQUESTED** [review]
sorry to come back now, but actually we shouldn't set `date` prop at all. date is optional and if it's not set, it's actually doing "latest".
It's better to do this because new Date() always will change ref and therefore always retrigger a re-rendering vs not setting a prop will be only updating when the countervalues are changing.

**Comment by hzheng-ledger** [comment]
> sorry to come back now, but actually we shouldn't set `date` prop at all. date is optional and if it's not set, it's actually doing "latest".
> It's better to do this because new Date() always will change ref and therefore always retrigger a re-rendering vs not setting a prop will be only updating when the countervalues are changing.

Thanks for the feedback. Fixed now

**Review by ghost — APPROVED** [review]
Ready for QA imho

**Review by ghost — APPROVED** [review]

**Review by nabil-brn — APPROVED** [review]

**Pull request merged**
